# Author: kk.Fang(fkfkbill@gmail.com)

ARG BASE_IMAGE="probe.yamucloud.com:8666/probe-server/python3.9-chrome:latest"
FROM $BASE_IMAGE
MAINTAINER bill

WORKDIR /project
COPY ../requirements.txt /tmp
RUN pip install -i https://pypi.doubanio.com/simple/ --no-cache-dir -r /tmp/requirements.txt \
  && rm -rf \
    /tmp/* \
    /usr/share/doc/* \
    /var/cache/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
ENV TZ=Asia/Shanghai PYTHONUNBUFFERED=x
COPY ../ /project
CMD ["python", "app.py"]
